In [7]:
import urllib.request

url = 'https://discover.data.vic.gov.au/api/3/action/datastore_search?resource_id=3b4c9b89-c976-49e7-8358-075fe3699297'  
fileobj = urllib.request.urlopen(url)
print(fileobj.read())

b'{"help": "https://discover.data.vic.gov.au/api/3/action/help_show?name=datastore_search", "success": true, "result": {"include_total": true, "limit": 100, "records_format": "objects", "resource_id": "3b4c9b89-c976-49e7-8358-075fe3699297", "total_estimation_threshold": null, "records": [{"_id":1,"location_id":"65","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":2,"location_id":"65","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":3,"location_id":"65","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":4,"location_id":"65","sensing_datetime":"2024-06-12T14:03:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:03","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":5,"location_id":"65","sensing_datetime":"2024-06-12T14:07:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:07","direction_1":"1","direction_2":"1","total_of_directions":"2"},{"_id":6,"location_id":"66","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":7,"location_id":"66","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"5","direction_2":"1","total_of_directions":"6"},{"_id":8,"location_id":"78","sensing_datetime":"2024-06-12T14:04:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:04","direction_1":"1","direction_2":"1","total_of_directions":"2"},{"_id":9,"location_id":"84","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"2","direction_2":"4","total_of_directions":"6"},{"_id":10,"location_id":"84","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":11,"location_id":"107","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"3","direction_2":"1","total_of_directions":"4"},{"_id":12,"location_id":"131","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"5","direction_2":"1","total_of_directions":"6"},{"_id":13,"location_id":"131","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":14,"location_id":"132","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":15,"location_id":"133","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"3","direction_2":"2","total_of_directions":"5"},{"_id":16,"location_id":"134","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"1","direction_2":"8","total_of_directions":"9"},{"_id":17,"location_id":"134","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"1","direction_2":"5","total_of_directions":"6"},{"_id":18,"location_id":"135","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"1","direction_2":"6","total_of_directions":"7"},{"_id":19,"location_id":"1","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":20,"location_id":"1","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":21,"location_id":"1","sensing_datetime":"2024-06-12T14:06:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:06","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":22,"location_id":"1","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":23,"location_id":"2","sensing_datetime":"2024-06-12T14:09:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:09","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":24,"location_id":"9","sensing_datetime":"2024-06-12T14:06:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:06","direction_1":"1","direction_2":"1","total_of_directions":"2"},{"_id":25,"location_id":"12","sensing_datetime":"2024-06-12T14:09:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:09","direction_1":"2","direction_2":"2","total_of_directions":"4"},{"_id":26,"location_id":"19","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"2","direction_2":"3","total_of_directions":"5"},{"_id":27,"location_id":"19","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"3","direction_2":"0","total_of_directions":"3"},{"_id":28,"location_id":"19","sensing_datetime":"2024-06-12T14:07:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:07","direction_1":"0","direction_2":"3","total_of_directions":"3"},{"_id":29,"location_id":"19","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":30,"location_id":"20","sensing_datetime":"2024-06-12T14:01:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:01","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":31,"location_id":"23","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":32,"location_id":"23","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":33,"location_id":"24","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"0","direction_2":"3","total_of_directions":"3"},{"_id":34,"location_id":"24","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":35,"location_id":"24","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":36,"location_id":"24","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":37,"location_id":"24","sensing_datetime":"2024-06-12T14:06:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:06","direction_1":"3","direction_2":"1","total_of_directions":"4"},{"_id":38,"location_id":"25","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":39,"location_id":"27","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":40,"location_id":"27","sensing_datetime":"2024-06-12T14:01:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:01","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":41,"location_id":"30","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":42,"location_id":"30","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":43,"location_id":"30","sensing_datetime":"2024-06-12T13:59:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:59","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":44,"location_id":"30","sensing_datetime":"2024-06-12T14:01:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:01","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":45,"location_id":"30","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"4","direction_2":"0","total_of_directions":"4"},{"_id":46,"location_id":"35","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":47,"location_id":"35","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":48,"location_id":"35","sensing_datetime":"2024-06-12T14:03:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:03","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":49,"location_id":"35","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"1","direction_2":"3","total_of_directions":"4"},{"_id":50,"location_id":"35","sensing_datetime":"2024-06-12T14:09:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:09","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":51,"location_id":"46","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":52,"location_id":"46","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"1","direction_2":"3","total_of_directions":"4"},{"_id":53,"location_id":"48","sensing_datetime":"2024-06-12T14:04:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:04","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":54,"location_id":"48","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"5","direction_2":"0","total_of_directions":"5"},{"_id":55,"location_id":"49","sensing_datetime":"2024-06-12T13:59:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:59","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":56,"location_id":"49","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":57,"location_id":"49","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":58,"location_id":"49","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":59,"location_id":"53","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"3","direction_2":"1","total_of_directions":"4"},{"_id":60,"location_id":"56","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":61,"location_id":"56","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":62,"location_id":"58","sensing_datetime":"2024-06-12T14:03:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:03","direction_1":"1","direction_2":"1","total_of_directions":"2"},{"_id":63,"location_id":"58","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"0","direction_2":"3","total_of_directions":"3"},{"_id":64,"location_id":"62","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"1","direction_2":"1","total_of_directions":"2"},{"_id":65,"location_id":"62","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":66,"location_id":"62","sensing_datetime":"2024-06-12T14:07:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:07","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":67,"location_id":"62","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":68,"location_id":"63","sensing_datetime":"2024-06-12T14:09:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:09","direction_1":"3","direction_2":"1","total_of_directions":"4"},{"_id":69,"location_id":"67","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":70,"location_id":"68","sensing_datetime":"2024-06-12T14:04:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:04","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":71,"location_id":"72","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":72,"location_id":"72","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":73,"location_id":"72","sensing_datetime":"2024-06-12T14:03:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:03","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":74,"location_id":"76","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":75,"location_id":"79","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":76,"location_id":"79","sensing_datetime":"2024-06-12T13:59:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:59","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":77,"location_id":"79","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":78,"location_id":"109","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":79,"location_id":"117","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"1","direction_2":"3","total_of_directions":"4"},{"_id":80,"location_id":"117","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":81,"location_id":"117","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"3","direction_2":"3","total_of_directions":"6"},{"_id":82,"location_id":"141","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":83,"location_id":"3","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"4","direction_2":"1","total_of_directions":"5"},{"_id":84,"location_id":"3","sensing_datetime":"2024-06-12T14:01:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:01","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":85,"location_id":"3","sensing_datetime":"2024-06-12T14:06:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:06","direction_1":"0","direction_2":"3","total_of_directions":"3"},{"_id":86,"location_id":"3","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"3","direction_2":"3","total_of_directions":"6"},{"_id":87,"location_id":"4","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"0","direction_2":"3","total_of_directions":"3"},{"_id":88,"location_id":"4","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":89,"location_id":"4","sensing_datetime":"2024-06-12T13:59:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:59","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":90,"location_id":"4","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"0","direction_2":"4","total_of_directions":"4"},{"_id":91,"location_id":"5","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"3","direction_2":"0","total_of_directions":"3"},{"_id":92,"location_id":"5","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"3","direction_2":"1","total_of_directions":"4"},{"_id":93,"location_id":"6","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":94,"location_id":"6","sensing_datetime":"2024-06-12T14:07:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:07","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":95,"location_id":"6","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"6","direction_2":"0","total_of_directions":"6"},{"_id":96,"location_id":"6","sensing_datetime":"2024-06-12T14:09:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:09","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":97,"location_id":"14","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"3","direction_2":"0","total_of_directions":"3"},{"_id":98,"location_id":"21","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":99,"location_id":"21","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"7","direction_2":"1","total_of_directions":"8"},{"_id":100,"location_id":"21","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"1","direction_2":"4","total_of_directions":"5"}], "fields": [{"id": "_id", "type": "int"}, {"id": "location_id", "type": "text"}, {"id": "sensing_datetime", "type": "text"}, {"id": "sensing_date", "type": "text"}, {"id": "sensing_time", "type": "text"}, {"id": "direction_1", "type": "text"}, {"id": "direction_2", "type": "text"}, {"id": "total_of_directions", "type": "text"}], "_links": {"start": "/api/3/action/datastore_search?resource_id=3b4c9b89-c976-49e7-8358-075fe3699297", "next": "/api/3/action/datastore_search?resource_id=3b4c9b89-c976-49e7-8358-075fe3699297&offset=100"}, "total": 933934, "total_was_estimated": false}}'

In [15]:
import urllib.request
import json 

url = 'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/pedestrian-counting-system-past-hour-counts-per-minute/records?limit=20'

fileobj = urllib.request.urlopen(url)
response = fileobj.read()

# Convert bytes to string by decoding
response_str = response.decode('utf-8')

# Parse JSON
data = json.loads(response_str)

In [18]:
data

{'total_count': 41913,
 'results': [{'location_id': 181,
   'sensing_datetime': '2025-04-13T14:00:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:00',
   'direction_1': 3,
   'direction_2': 2,
   'total_of_directions': 5},
  {'location_id': 181,
   'sensing_datetime': '2025-04-13T14:06:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:06',
   'direction_1': 2,
   'direction_2': 3,
   'total_of_directions': 5},
  {'location_id': 181,
   'sensing_datetime': '2025-04-13T14:08:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:08',
   'direction_1': 8,
   'direction_2': 6,
   'total_of_directions': 14},
  {'location_id': 3,
   'sensing_datetime': '2025-04-13T14:03:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:03',
   'direction_1': 9,
   'direction_2': 0,
   'total_of_directions': 9},
  {'location_id': 3,
   'sensing_datetime': '2025-04-13T14:07:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:07',
   'direction_1': 5,
   'direction_2': 2,
   'total_of_directions': 7},
  {'location_id': 3,
   'sensing_datetime': '2025-04-13T14:09:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:09',
   'direction_1': 3,
   'direction_2': 0,
   'total_of_directions': 3},
  {'location_id': 4,
   'sensing_datetime': '2025-04-13T13:55:00+00:00',
   'sensing_date': '2025-04-13',
   'sensing_time': '23:55',
   'direction_1': 1,
   'direction_2': 1,
   'total_of_directions': 2},
  {'location_id': 4,
   'sensing_datetime': '2025-04-13T14:02:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:02',
   'direction_1': 0,
   'direction_2': 2,
   'total_of_directions': 2},
  {'location_id': 4,
   'sensing_datetime': '2025-04-13T14:03:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:03',
   'direction_1': 2,
   'direction_2': 1,
   'total_of_directions': 3},
  {'location_id': 4,
   'sensing_datetime': '2025-04-13T14:08:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:08',
   'direction_1': 3,
   'direction_2': 3,
   'total_of_directions': 6},
  {'location_id': 5,
   'sensing_datetime': '2025-04-13T13:55:00+00:00',
   'sensing_date': '2025-04-13',
   'sensing_time': '23:55',
   'direction_1': 13,
   'direction_2': 3,
   'total_of_directions': 16},
  {'location_id': 6,
   'sensing_datetime': '2025-04-13T13:58:00+00:00',
   'sensing_date': '2025-04-13',
   'sensing_time': '23:58',
   'direction_1': 7,
   'direction_2': 5,
   'total_of_directions': 12},
  {'location_id': 6,
   'sensing_datetime': '2025-04-13T14:00:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:00',
   'direction_1': 2,
   'direction_2': 9,
   'total_of_directions': 11},
  {'location_id': 6,
   'sensing_datetime': '2025-04-13T14:02:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:02',
   'direction_1': 0,
   'direction_2': 1,
   'total_of_directions': 1},
  {'location_id': 6,
   'sensing_datetime': '2025-04-13T14:06:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:06',
   'direction_1': 2,
   'direction_2': 3,
   'total_of_directions': 5},
  {'location_id': 6,
   'sensing_datetime': '2025-04-13T14:08:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:08',
   'direction_1': 2,
   'direction_2': 0,
   'total_of_directions': 2},
  {'location_id': 14,
   'sensing_datetime': '2025-04-13T13:59:00+00:00',
   'sensing_date': '2025-04-13',
   'sensing_time': '23:59',
   'direction_1': 2,
   'direction_2': 0,
   'total_of_directions': 2},
  {'location_id': 14,
   'sensing_datetime': '2025-04-13T14:02:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:02',
   'direction_1': 1,
   'direction_2': 0,
   'total_of_directions': 1},
  {'location_id': 21,
   'sensing_datetime': '2025-04-13T14:05:00+00:00',
   'sensing_date': '2025-04-14',
   'sensing_time': '00:05',
   'direction_1': 7,
   'direction_2': 0,
   'total_of_directions': 7},
  {'location_id': 28,
   'sensing_datetime': '2025-04-13T13:59:00+00:00',
   'sensing_date': '2025-04-13',
   'sensing_time': '23:59',
   'direction_1': 1,
   'direction_2': 0,
   'total_of_directions': 1}]}

In [20]:
import pandas as pd
records = data['results']
df = pd.DataFrame(records)

In [21]:
df

,location_id,sensing_datetime,sensing_date,sensing_time,direction_1,direction_2,total_of_directions
0,181,2025-04-13T14:00:00+00:00,2025-04-14,00:00,3,2,5
1,181,2025-04-13T14:06:00+00:00,2025-04-14,00:06,2,3,5
2,181,2025-04-13T14:08:00+00:00,2025-04-14,00:08,8,6,14
3,3,2025-04-13T14:03:00+00:00,2025-04-14,00:03,9,0,9
4,3,2025-04-13T14:07:00+00:00,2025-04-14,00:07,5,2,7
5,3,2025-04-13T14:09:00+00:00,2025-04-14,00:09,3,0,3
6,4,2025-04-13T13:55:00+00:00,2025-04-13,23:55,1,1,2
7,4,2025-04-13T14:02:00+00:00,2025-04-14,00:02,0,2,2
8,4,2025-04-13T14:03:00+00:00,2025-04-14,00:03,2,1,3
9,4,2025-04-13T14:08:00+00:00,2025-04-14,00:08,3,3,6
10,5,2025-04-13T13:55:00+00:00,2025-04-13,23:55,13,3,16
11,6,2025-04-13T13:58:00+00:00,2025-04-13,23:58,7,5,12
12,6,2025-04-13T14:00:00+00:00,2025-04-14,00:00,2,9,11
13,6,2025-04-13T14:02:00+00:00,2025-04-14,00:02,0,1,1
14,6,2025-04-13T14:06:00+00:00,2025-04-14,00:06,2,3,5
15,6,2025-04-13T14:08:00+00:00,2025-04-14,00:08,2,0,2
16,14,2025-04-13T13:59:00+00:00,2025-04-13,23:59,2,0,2
17,14,2025-04-13T14:02:00+00:00,2025-04-14,00:02,1,0,1
18,21,2025-04-13T14:05:00+00:00,2025-04-14,00:05,7,0,7
19,28,2025-04-13T13:59:00+00:00,2025-04-13,23:59,1,0,1

In [24]:
import datetime 
now = datetime.datetime.now()
five_minutes_ago = now - datetime.timedelta(minutes=5)
timestamp = five_minutes_ago.isoformat()
print(timestamp)

# Format the URL with a filter for the last 5 minutes
base_url = 'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/pedestrian-counting-system-past-hour-counts-per-minute/records'
filter_param = f'?where=date_time >= date\'{timestamp}\''
url = base_url + filter_param + '&limit=100' 

fileobj = urllib.request.urlopen(url)
response = fileobj.read()
response_str = response.decode('utf-8')

data = json.loads(response_str)
records = data['results']

df = pd.DataFrame(records)
df

2025-04-14T16:26:46.140800

InvalidURL: URL can't contain control characters. "/api/explore/v2.1/catalog/datasets/pedestrian-counting-system-past-hour-counts-per-minute/records?where=date_time >= date'2025-04-14T16:26:46.140800'&limit=100" (found at least ' ')

In [27]:
import pandas as pd
raw_light = pd.read_csv('raw/street-lights-with-emitted-lux-level-council-owned-lights-only.csv')
raw_light.head()

,geo_point_2d,geo_shape,prop_id,name,addresspt1,xorg,ext_id,asset_clas,label,asset_type,...,northing,str_id,addresspt,asset_subt,xsource,profile,xdate,xdrawing,mcc_id,roadseg_id
0,"-37.81373899955726, 144.9421289998664","{""coordinates"": [144.9421289998664, -37.813738...",0,NaN,0.0,ESG,210,NaN,6.549,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
1,"-37.81374400011677, 144.94213900036905","{""coordinates"": [144.94213900036905, -37.81374...",0,NaN,0.0,ESG,214,NaN,6.158,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
2,"-37.813802999768036, 144.94222000027733","{""coordinates"": [144.94222000027733, -37.81380...",0,NaN,0.0,ESG,251,NaN,54.448,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
3,"-37.81380999995285, 144.9422400005824","{""coordinates"": [144.9422400005824, -37.813809...",0,NaN,0.0,ESG,259,NaN,98.143,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
4,"-37.81351900001735, 144.94179300024945","{""coordinates"": [144.94179300024945, -37.81351...",0,NaN,0.0,ESG,77,NaN,18.280,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0

In [ ]:
# lighting data last updated at 20140916
raw_light['xdate'].drop_duplicates()

0    20140916
Name: xdate, dtype: int64

In [30]:
raw_light.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106037 entries, 0 to 106036
Data columns (total 21 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   geo_point_2d  106037 non-null  object
 1   geo_shape     106037 non-null  object
 2   prop_id       106037 non-null  int64
 3   name          0 non-null       float64
 4   addresspt1    106037 non-null  float64
 5   xorg          106037 non-null  object
 6   ext_id        106037 non-null  int64
 7   asset_clas    0 non-null       float64
 8   label         106037 non-null  float64
 9   asset_type    0 non-null       float64
 10  easting       106037 non-null  float64
 11  northing      106037 non-null  float64
 12  str_id        106037 non-null  int64
 13  addresspt     106037 non-null  int64
 14  asset_subt    0 non-null       float64
 15  xsource       0 non-null       float64
 16  profile       0 non-null       float64
 17  xdate         106037 non-null  int64
 18  xdrawing      0 non-null       float64
 19  mcc_id        106037 non-null  int64
 20  roadseg_id    106037 non-null  int64
dtypes: float64(11), int64(7), object(3)
memory usage: 17.0+ MB

In [31]:
raw_light[['prop_id', 'geo_point_2d', 'geo_shape']].nunique()

prop_id             1
geo_point_2d    97405
geo_shape       97405
dtype: int64

In [ ]:
raw_light['geo_point_2d']

97405

In [35]:
raw_light[raw_light['geo_shape'].str.contains('144.9421289998664')]

,geo_point_2d,geo_shape,prop_id,name,addresspt1,xorg,ext_id,asset_clas,label,asset_type,...,northing,str_id,addresspt,asset_subt,xsource,profile,xdate,xdrawing,mcc_id,roadseg_id
0,"-37.81373899955726, 144.9421289998664","{""coordinates"": [144.9421289998664, -37.813738...",0,NaN,0.0,ESG,210,NaN,6.549,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0

In [47]:
# geo_shape that occur more than once
duplicate_geo_shapes = raw_light['geo_shape'].value_counts()
# duplicate_geo_shapes = duplicate_geo_shapes[duplicate_geo_shapes > 1]
# raw_light[raw_light['geo_shape'].isin(duplicate_geo_shapes.index)]
# duplicate_geo_shapes

sample_geo_duplicate_geo_shapes = duplicate_geo_shapes.index[0]
raw_light[raw_light['geo_shape']==sample_geo_duplicate_geo_shapes].drop_duplicates()

,geo_point_2d,geo_shape,prop_id,name,addresspt1,xorg,ext_id,asset_clas,label,asset_type,...,northing,str_id,addresspt,asset_subt,xsource,profile,xdate,xdrawing,mcc_id,roadseg_id
518,"-37.80109000004725, 144.9702759997199","{""coordinates"": [144.9702759997199, -37.801090...",0,NaN,0.0,ESG,14705,NaN,1.564,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
519,"-37.80109000004725, 144.9702759997199","{""coordinates"": [144.9702759997199, -37.801090...",0,NaN,0.0,ESG,14729,NaN,1.564,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
525,"-37.80109000004725, 144.9702759997199","{""coordinates"": [144.9702759997199, -37.801090...",0,NaN,0.0,ESG,14918,NaN,1.564,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
526,"-37.80109000004725, 144.9702759997199","{""coordinates"": [144.9702759997199, -37.801090...",0,NaN,0.0,ESG,14934,NaN,1.564,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
527,"-37.80109000004725, 144.9702759997199","{""coordinates"": [144.9702759997199, -37.801090...",0,NaN,0.0,ESG,15240,NaN,1.564,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96510,"-37.80109000004725, 144.9702759997199","{""coordinates"": [144.9702759997199, -37.801090...",0,NaN,0.0,ESG,15182,NaN,1.564,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
96527,"-37.80109000004725, 144.9702759997199","{""coordinates"": [144.9702759997199, -37.801090...",0,NaN,0.0,ESG,15557,NaN,1.564,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
96528,"-37.80109000004725, 144.9702759997199","{""coordinates"": [144.9702759997199, -37.801090...",0,NaN,0.0,ESG,15567,NaN,1.564,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
96529,"-37.80109000004725, 144.9702759997199","{""coordinates"": [144.9702759997199, -37.801090...",0,NaN,0.0,ESG,15584,NaN,1.564,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
96530,"-37.80109000004725, 144.9702759997199","{""coordinates"": [144.9702759997199, -37.801090...",0,NaN,0.0,ESG,15605,NaN,1.564,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0

In [ ]:
dedup_light = raw_light[['geo_point_2d', 'geo_shape', 'label']].drop_duplicates()
print(dedup_light.shape)
dedup_light.nunique()
# still has some duplications after this step

(99421, 3)

geo_point_2d    97405
geo_shape       97405
label            1016
dtype: int64

In [60]:

duplicate_geo_shapes = dedup_light['geo_shape'].value_counts()
duplicate_geo_shapes = duplicate_geo_shapes[duplicate_geo_shapes > 1]

duplicate_geo_shapes

raw_light[raw_light['geo_shape'].isin(duplicate_geo_shapes.index)].sort_values('geo_shape')

,geo_point_2d,geo_shape,prop_id,name,addresspt1,xorg,ext_id,asset_clas,label,asset_type,...,northing,str_id,addresspt,asset_subt,xsource,profile,xdate,xdrawing,mcc_id,roadseg_id
56786,"-37.79690900005227, 144.9233400005101","{""coordinates"": [144.9233400005101, -37.796909...",0,NaN,0.0,ESG,55512,NaN,12.903,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
84552,"-37.79690900005227, 144.9233400005101","{""coordinates"": [144.9233400005101, -37.796909...",0,NaN,0.0,ESG,55510,NaN,14.272,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
68670,"-37.79690900005227, 144.9233400005101","{""coordinates"": [144.9233400005101, -37.796909...",0,NaN,0.0,ESG,55511,NaN,13.881,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
20423,"-37.79690900005227, 144.9233400005101","{""coordinates"": [144.9233400005101, -37.796909...",0,NaN,0.0,ESG,55514,NaN,11.046,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
78499,"-37.79690900005227, 144.9233400005101","{""coordinates"": [144.9233400005101, -37.796909...",0,NaN,0.0,ESG,55505,NaN,13.001,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10565,"-37.81318300034135, 144.98933400014678","{""coordinates"": [144.98933400014678, -37.81318...",0,NaN,0.0,ESG,23806,NaN,2.737,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
57875,"-37.81317499967046, 144.9893340002478","{""coordinates"": [144.9893340002478, -37.813174...",0,NaN,0.0,ESG,23785,NaN,5.083,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
68524,"-37.81317499967046, 144.9893340002478","{""coordinates"": [144.9893340002478, -37.813174...",0,NaN,0.0,ESG,23784,NaN,5.181,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
18969,"-37.81317599998194, 144.98933400037097","{""coordinates"": [144.98933400037097, -37.81317...",0,NaN,0.0,ESG,23787,NaN,4.692,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
31647,"-37.81317599998194, 144.98933400037097","{""coordinates"": [144.98933400037097, -37.81317...",0,NaN,0.0,ESG,23786,NaN,4.888,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0