# Pedestrian Data (Historical 2024-2025)

In [139]:
import pandas as pd
raw_ped = pd.read_csv('merged_pedestrian_counts.csv')
sensor_location = pd.read_csv('raw/pedestrian-counting-system-sensor-locations.csv')

In [140]:
raw_ped.head()

,ID,Location_ID,Sensing_Date,HourDay,Direction_1,Direction_2,Total_of_Directions,Sensor_Name,Location
0,672220240621,67,2024-06-21,22,175,307,482,FLDegS_T,"-37.81688755, 144.96562569"
1,1091020240724,109,2024-07-24,10,34,165,199,LatWill_T,"-37.81193681, 144.95621105"
2,2420240919,2,2024-09-19,4,1,2,3,Bou283_T,"-37.81380668, 144.96516718"
3,492220241018,49,2024-10-18,22,140,124,264,Eli501_T,"-37.80730068, 144.95956055"
4,651120240731,65,2024-07-31,11,703,384,1087,SwaCs_T,"-37.81569416, 144.9668064"

In [ ]:
sensor_location.head()

,Location_ID,Sensor_Description,Sensor_Name,Installation_Date,Note,Location_Type,Status,Direction_1,Direction_2,Latitude,Longitude,Location
0,24,Spencer St-Collins St (North),Col620_T,2013-09-02,NaN,Outdoor,A,East,West,-37.818880,144.954492,"-37.81887963, 144.95449198"
1,25,Melbourne Convention Exhibition Centre,MCEC_T,2013-08-28,NaN,Outdoor,A,East,West,-37.824018,144.956044,"-37.82401776, 144.95604426"
2,36,Queen St (West),Que85_T,2015-01-20,"Pushbox Upgrade, 03/08/2023",Outdoor,A,North,South,-37.816525,144.961211,"-37.81652527, 144.96121062"
3,41,Flinders La-Swanston St (West),Swa31,2017-06-29,NaN,Outdoor,A,North,South,-37.816686,144.966897,"-37.81668634, 144.96689733"
4,44,Tin Alley-Swanston St (West),UM3_T,2015-04-15,"Pushbox Upgrade, 30/06/2023",Outdoor,A,North,South,-37.796987,144.964413,"-37.79698741, 144.96441306"

In [147]:
print(sensor_location.shape)
sensor_location.nunique()

(132, 12)

Location_ID           132
Sensor_Description    131
Sensor_Name           130
Installation_Date      78
Note                   20
Location_Type           2
Status                  1
Direction_1             3
Direction_2             3
Latitude              132
Longitude             132
Location              132
dtype: int64

In [148]:
ped_df = pd.merge(raw_ped[['Location_ID', 
                           'Sensing_Date', 
                           'HourDay',
                           'Direction_1',
                           'Direction_2',
                           'Total_of_Directions'
                           ]],
                  sensor_location[['Location_ID', 
                                   'Sensor_Description', 
                                   'Sensor_Name', 
                                   'Location_Type', 
                                   'Latitude',
                                   'Longitude',
                                   'Status']], 
                  on='Location_ID', how='left')
ped_df.columns = ped_df.columns.str.replace(r'[^\w]', '_', regex=True).str.lower()
# ped_df['latitude'] = ped_df['location'].str.split(', ').str[0].astype(float)
# ped_df['longitude'] = ped_df['location'].str.split(', ').str[1].astype(float)
ped_df.head()

,location_id,sensing_date,hourday,direction_1,direction_2,total_of_directions,sensor_description,sensor_name,location_type,latitude,longitude,status
0,67,2024-06-21,22,175,307,482,Flinders Ln -Degraves St (South),FLDegS_T,Outdoor,-37.816888,144.965626,A
1,109,2024-07-24,10,34,165,199,La Trobe St- William St (South),LatWill_T,Outdoor,-37.811937,144.956211,A
2,2,2024-09-19,4,1,2,3,Bourke Street Mall (South),Bou283_T,Outdoor,-37.813807,144.965167,A
3,49,2024-10-18,22,140,124,264,QVM-Therry St (South),Eli501_T,Outdoor,-37.807301,144.959561,A
4,65,2024-07-31,11,703,384,1087,Swanston St - City Square,SwaCs_T,Outdoor,-37.815694,144.966806,A

In [149]:
print(ped_df.shape)
ped_df.nunique()

(917512, 12)

location_id              97
sensing_date            479
hourday                  24
direction_1            2934
direction_2            2988
total_of_directions    4544
sensor_description       96
sensor_name              95
location_type             1
latitude                 97
longitude                97
status                    1
dtype: int64

In [150]:
# Prepare export data
ped_df.to_csv('pedestrian.csv', index=False)

# Testing: Pedestrian Data (API)

In [1]:
import urllib.request

url = 'https://discover.data.vic.gov.au/api/3/action/datastore_search?resource_id=3b4c9b89-c976-49e7-8358-075fe3699297'  
fileobj = urllib.request.urlopen(url)
print(fileobj.read())

b'{"help": "https://discover.data.vic.gov.au/api/3/action/help_show?name=datastore_search", "success": true, "result": {"include_total": true, "limit": 100, "records_format": "objects", "resource_id": "3b4c9b89-c976-49e7-8358-075fe3699297", "total_estimation_threshold": null, "records": [{"_id":1,"location_id":"65","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":2,"location_id":"65","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":3,"location_id":"65","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":4,"location_id":"65","sensing_datetime":"2024-06-12T14:03:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:03","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":5,"location_id":"65","sensing_datetime":"2024-06-12T14:07:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:07","direction_1":"1","direction_2":"1","total_of_directions":"2"},{"_id":6,"location_id":"66","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":7,"location_id":"66","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"5","direction_2":"1","total_of_directions":"6"},{"_id":8,"location_id":"78","sensing_datetime":"2024-06-12T14:04:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:04","direction_1":"1","direction_2":"1","total_of_directions":"2"},{"_id":9,"location_id":"84","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"2","direction_2":"4","total_of_directions":"6"},{"_id":10,"location_id":"84","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":11,"location_id":"107","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"3","direction_2":"1","total_of_directions":"4"},{"_id":12,"location_id":"131","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"5","direction_2":"1","total_of_directions":"6"},{"_id":13,"location_id":"131","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":14,"location_id":"132","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":15,"location_id":"133","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"3","direction_2":"2","total_of_directions":"5"},{"_id":16,"location_id":"134","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"1","direction_2":"8","total_of_directions":"9"},{"_id":17,"location_id":"134","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"1","direction_2":"5","total_of_directions":"6"},{"_id":18,"location_id":"135","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"1","direction_2":"6","total_of_directions":"7"},{"_id":19,"location_id":"1","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":20,"location_id":"1","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":21,"location_id":"1","sensing_datetime":"2024-06-12T14:06:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:06","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":22,"location_id":"1","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":23,"location_id":"2","sensing_datetime":"2024-06-12T14:09:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:09","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":24,"location_id":"9","sensing_datetime":"2024-06-12T14:06:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:06","direction_1":"1","direction_2":"1","total_of_directions":"2"},{"_id":25,"location_id":"12","sensing_datetime":"2024-06-12T14:09:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:09","direction_1":"2","direction_2":"2","total_of_directions":"4"},{"_id":26,"location_id":"19","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"2","direction_2":"3","total_of_directions":"5"},{"_id":27,"location_id":"19","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"3","direction_2":"0","total_of_directions":"3"},{"_id":28,"location_id":"19","sensing_datetime":"2024-06-12T14:07:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:07","direction_1":"0","direction_2":"3","total_of_directions":"3"},{"_id":29,"location_id":"19","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":30,"location_id":"20","sensing_datetime":"2024-06-12T14:01:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:01","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":31,"location_id":"23","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":32,"location_id":"23","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":33,"location_id":"24","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"0","direction_2":"3","total_of_directions":"3"},{"_id":34,"location_id":"24","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":35,"location_id":"24","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":36,"location_id":"24","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":37,"location_id":"24","sensing_datetime":"2024-06-12T14:06:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:06","direction_1":"3","direction_2":"1","total_of_directions":"4"},{"_id":38,"location_id":"25","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":39,"location_id":"27","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":40,"location_id":"27","sensing_datetime":"2024-06-12T14:01:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:01","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":41,"location_id":"30","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":42,"location_id":"30","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":43,"location_id":"30","sensing_datetime":"2024-06-12T13:59:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:59","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":44,"location_id":"30","sensing_datetime":"2024-06-12T14:01:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:01","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":45,"location_id":"30","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"4","direction_2":"0","total_of_directions":"4"},{"_id":46,"location_id":"35","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":47,"location_id":"35","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":48,"location_id":"35","sensing_datetime":"2024-06-12T14:03:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:03","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":49,"location_id":"35","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"1","direction_2":"3","total_of_directions":"4"},{"_id":50,"location_id":"35","sensing_datetime":"2024-06-12T14:09:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:09","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":51,"location_id":"46","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":52,"location_id":"46","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"1","direction_2":"3","total_of_directions":"4"},{"_id":53,"location_id":"48","sensing_datetime":"2024-06-12T14:04:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:04","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":54,"location_id":"48","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"5","direction_2":"0","total_of_directions":"5"},{"_id":55,"location_id":"49","sensing_datetime":"2024-06-12T13:59:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:59","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":56,"location_id":"49","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":57,"location_id":"49","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":58,"location_id":"49","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":59,"location_id":"53","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"3","direction_2":"1","total_of_directions":"4"},{"_id":60,"location_id":"56","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":61,"location_id":"56","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":62,"location_id":"58","sensing_datetime":"2024-06-12T14:03:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:03","direction_1":"1","direction_2":"1","total_of_directions":"2"},{"_id":63,"location_id":"58","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"0","direction_2":"3","total_of_directions":"3"},{"_id":64,"location_id":"62","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"1","direction_2":"1","total_of_directions":"2"},{"_id":65,"location_id":"62","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":66,"location_id":"62","sensing_datetime":"2024-06-12T14:07:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:07","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":67,"location_id":"62","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":68,"location_id":"63","sensing_datetime":"2024-06-12T14:09:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:09","direction_1":"3","direction_2":"1","total_of_directions":"4"},{"_id":69,"location_id":"67","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"0","direction_2":"2","total_of_directions":"2"},{"_id":70,"location_id":"68","sensing_datetime":"2024-06-12T14:04:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:04","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":71,"location_id":"72","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":72,"location_id":"72","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":73,"location_id":"72","sensing_datetime":"2024-06-12T14:03:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:03","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":74,"location_id":"76","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":75,"location_id":"79","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":76,"location_id":"79","sensing_datetime":"2024-06-12T13:59:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:59","direction_1":"0","direction_2":"1","total_of_directions":"1"},{"_id":77,"location_id":"79","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"1","direction_2":"2","total_of_directions":"3"},{"_id":78,"location_id":"109","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":79,"location_id":"117","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"1","direction_2":"3","total_of_directions":"4"},{"_id":80,"location_id":"117","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":81,"location_id":"117","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"3","direction_2":"3","total_of_directions":"6"},{"_id":82,"location_id":"141","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":83,"location_id":"3","sensing_datetime":"2024-06-12T13:58:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:58","direction_1":"4","direction_2":"1","total_of_directions":"5"},{"_id":84,"location_id":"3","sensing_datetime":"2024-06-12T14:01:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:01","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":85,"location_id":"3","sensing_datetime":"2024-06-12T14:06:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:06","direction_1":"0","direction_2":"3","total_of_directions":"3"},{"_id":86,"location_id":"3","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"3","direction_2":"3","total_of_directions":"6"},{"_id":87,"location_id":"4","sensing_datetime":"2024-06-12T13:56:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:56","direction_1":"0","direction_2":"3","total_of_directions":"3"},{"_id":88,"location_id":"4","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":89,"location_id":"4","sensing_datetime":"2024-06-12T13:59:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:59","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":90,"location_id":"4","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"0","direction_2":"4","total_of_directions":"4"},{"_id":91,"location_id":"5","sensing_datetime":"2024-06-12T13:55:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:55","direction_1":"3","direction_2":"0","total_of_directions":"3"},{"_id":92,"location_id":"5","sensing_datetime":"2024-06-12T14:05:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:05","direction_1":"3","direction_2":"1","total_of_directions":"4"},{"_id":93,"location_id":"6","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"2","direction_2":"1","total_of_directions":"3"},{"_id":94,"location_id":"6","sensing_datetime":"2024-06-12T14:07:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:07","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":95,"location_id":"6","sensing_datetime":"2024-06-12T14:08:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:08","direction_1":"6","direction_2":"0","total_of_directions":"6"},{"_id":96,"location_id":"6","sensing_datetime":"2024-06-12T14:09:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:09","direction_1":"1","direction_2":"0","total_of_directions":"1"},{"_id":97,"location_id":"14","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"3","direction_2":"0","total_of_directions":"3"},{"_id":98,"location_id":"21","sensing_datetime":"2024-06-12T13:57:00+00:00","sensing_date":"2024-06-12","sensing_time":"23:57","direction_1":"2","direction_2":"0","total_of_directions":"2"},{"_id":99,"location_id":"21","sensing_datetime":"2024-06-12T14:00:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:00","direction_1":"7","direction_2":"1","total_of_directions":"8"},{"_id":100,"location_id":"21","sensing_datetime":"2024-06-12T14:02:00+00:00","sensing_date":"2024-06-13","sensing_time":"00:02","direction_1":"1","direction_2":"4","total_of_directions":"5"}], "fields": [{"id": "_id", "type": "int"}, {"id": "location_id", "type": "text"}, {"id": "sensing_datetime", "type": "text"}, {"id": "sensing_date", "type": "text"}, {"id": "sensing_time", "type": "text"}, {"id": "direction_1", "type": "text"}, {"id": "direction_2", "type": "text"}, {"id": "total_of_directions", "type": "text"}], "_links": {"start": "/api/3/action/datastore_search?resource_id=3b4c9b89-c976-49e7-8358-075fe3699297", "next": "/api/3/action/datastore_search?resource_id=3b4c9b89-c976-49e7-8358-075fe3699297&offset=100"}, "total": 933934, "total_was_estimated": false}}'

In [2]:
import urllib.request
import json 

url = 'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/pedestrian-counting-system-past-hour-counts-per-minute/records?limit=20'

fileobj = urllib.request.urlopen(url)
response = fileobj.read()

# Convert bytes to string by decoding
response_str = response.decode('utf-8')

# Parse JSON
data = json.loads(response_str)

In [3]:
data

{'total_count': 48116,
 'results': [{'location_id': 181,
   'sensing_datetime': '2025-04-22T14:02:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:02',
   'direction_1': 2,
   'direction_2': 3,
   'total_of_directions': 5},
  {'location_id': 181,
   'sensing_datetime': '2025-04-22T14:05:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:05',
   'direction_1': 2,
   'direction_2': 4,
   'total_of_directions': 6},
  {'location_id': 181,
   'sensing_datetime': '2025-04-22T14:09:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:09',
   'direction_1': 0,
   'direction_2': 2,
   'total_of_directions': 2},
  {'location_id': 3,
   'sensing_datetime': '2025-04-22T13:56:00+00:00',
   'sensing_date': '2025-04-22',
   'sensing_time': '23:56',
   'direction_1': 6,
   'direction_2': 2,
   'total_of_directions': 8},
  {'location_id': 3,
   'sensing_datetime': '2025-04-22T14:02:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:02',
   'direction_1': 5,
   'direction_2': 4,
   'total_of_directions': 9},
  {'location_id': 3,
   'sensing_datetime': '2025-04-22T14:05:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:05',
   'direction_1': 5,
   'direction_2': 2,
   'total_of_directions': 7},
  {'location_id': 3,
   'sensing_datetime': '2025-04-22T14:07:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:07',
   'direction_1': 2,
   'direction_2': 1,
   'total_of_directions': 3},
  {'location_id': 4,
   'sensing_datetime': '2025-04-22T14:01:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:01',
   'direction_1': 6,
   'direction_2': 1,
   'total_of_directions': 7},
  {'location_id': 4,
   'sensing_datetime': '2025-04-22T14:05:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:05',
   'direction_1': 1,
   'direction_2': 6,
   'total_of_directions': 7},
  {'location_id': 5,
   'sensing_datetime': '2025-04-22T14:05:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:05',
   'direction_1': 4,
   'direction_2': 10,
   'total_of_directions': 14},
  {'location_id': 6,
   'sensing_datetime': '2025-04-22T13:56:00+00:00',
   'sensing_date': '2025-04-22',
   'sensing_time': '23:56',
   'direction_1': 5,
   'direction_2': 3,
   'total_of_directions': 8},
  {'location_id': 6,
   'sensing_datetime': '2025-04-22T13:59:00+00:00',
   'sensing_date': '2025-04-22',
   'sensing_time': '23:59',
   'direction_1': 4,
   'direction_2': 1,
   'total_of_directions': 5},
  {'location_id': 14,
   'sensing_datetime': '2025-04-22T14:02:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:02',
   'direction_1': 0,
   'direction_2': 1,
   'total_of_directions': 1},
  {'location_id': 14,
   'sensing_datetime': '2025-04-22T14:09:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:09',
   'direction_1': 0,
   'direction_2': 2,
   'total_of_directions': 2},
  {'location_id': 36,
   'sensing_datetime': '2025-04-22T14:02:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:02',
   'direction_1': 0,
   'direction_2': 2,
   'total_of_directions': 2},
  {'location_id': 37,
   'sensing_datetime': '2025-04-22T14:01:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:01',
   'direction_1': 0,
   'direction_2': 1,
   'total_of_directions': 1},
  {'location_id': 41,
   'sensing_datetime': '2025-04-22T13:56:00+00:00',
   'sensing_date': '2025-04-22',
   'sensing_time': '23:56',
   'direction_1': 0,
   'direction_2': 1,
   'total_of_directions': 1},
  {'location_id': 41,
   'sensing_datetime': '2025-04-22T14:01:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:01',
   'direction_1': 0,
   'direction_2': 7,
   'total_of_directions': 7},
  {'location_id': 41,
   'sensing_datetime': '2025-04-22T14:06:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:06',
   'direction_1': 8,
   'direction_2': 0,
   'total_of_directions': 8},
  {'location_id': 45,
   'sensing_datetime': '2025-04-22T14:09:00+00:00',
   'sensing_date': '2025-04-23',
   'sensing_time': '00:09',
   'direction_1': 1,
   'direction_2': 3,
   'total_of_directions': 4}]}

In [4]:
import pandas as pd
records = data['results']
df = pd.DataFrame(records)

In [5]:
df

,location_id,sensing_datetime,sensing_date,sensing_time,direction_1,direction_2,total_of_directions
0,181,2025-04-22T14:02:00+00:00,2025-04-23,00:02,2,3,5
1,181,2025-04-22T14:05:00+00:00,2025-04-23,00:05,2,4,6
2,181,2025-04-22T14:09:00+00:00,2025-04-23,00:09,0,2,2
3,3,2025-04-22T13:56:00+00:00,2025-04-22,23:56,6,2,8
4,3,2025-04-22T14:02:00+00:00,2025-04-23,00:02,5,4,9
5,3,2025-04-22T14:05:00+00:00,2025-04-23,00:05,5,2,7
6,3,2025-04-22T14:07:00+00:00,2025-04-23,00:07,2,1,3
7,4,2025-04-22T14:01:00+00:00,2025-04-23,00:01,6,1,7
8,4,2025-04-22T14:05:00+00:00,2025-04-23,00:05,1,6,7
9,5,2025-04-22T14:05:00+00:00,2025-04-23,00:05,4,10,14
10,6,2025-04-22T13:56:00+00:00,2025-04-22,23:56,5,3,8
11,6,2025-04-22T13:59:00+00:00,2025-04-22,23:59,4,1,5
12,14,2025-04-22T14:02:00+00:00,2025-04-23,00:02,0,1,1
13,14,2025-04-22T14:09:00+00:00,2025-04-23,00:09,0,2,2
14,36,2025-04-22T14:02:00+00:00,2025-04-23,00:02,0,2,2
15,37,2025-04-22T14:01:00+00:00,2025-04-23,00:01,0,1,1
16,41,2025-04-22T13:56:00+00:00,2025-04-22,23:56,0,1,1
17,41,2025-04-22T14:01:00+00:00,2025-04-23,00:01,0,7,7
18,41,2025-04-22T14:06:00+00:00,2025-04-23,00:06,8,0,8
19,45,2025-04-22T14:09:00+00:00,2025-04-23,00:09,1,3,4

In [6]:
import datetime 
now = datetime.datetime.now()
five_minutes_ago = now - datetime.timedelta(minutes=5)
timestamp = five_minutes_ago.isoformat()
print(timestamp)

# Format the URL with a filter for the last 5 minutes
base_url = 'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/pedestrian-counting-system-past-hour-counts-per-minute/records'
filter_param = f'?where=date_time >= date\'{timestamp}\''
url = base_url + filter_param + '&limit=100' 

fileobj = urllib.request.urlopen(url)
response = fileobj.read()
response_str = response.decode('utf-8')

data = json.loads(response_str)
records = data['results']

df = pd.DataFrame(records)
df

2025-04-23T18:19:54.249939

InvalidURL: URL can't contain control characters. "/api/explore/v2.1/catalog/datasets/pedestrian-counting-system-past-hour-counts-per-minute/records?where=date_time >= date'2025-04-23T18:19:54.249939'&limit=100" (found at least ' ')

# Lighting Data

In [ ]:
raw_light = pd.read_csv('raw/street-lights-with-emitted-lux-level-council-owned-lights-only.csv')
raw_light.head()

,geo_point_2d,geo_shape,prop_id,name,addresspt1,xorg,ext_id,asset_clas,label,asset_type,...,northing,str_id,addresspt,asset_subt,xsource,profile,xdate,xdrawing,mcc_id,roadseg_id
0,"-37.81373899955726, 144.9421289998664","{""coordinates"": [144.9421289998664, -37.813738...",0,NaN,0.0,ESG,210,NaN,6.549,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
1,"-37.81374400011677, 144.94213900036905","{""coordinates"": [144.94213900036905, -37.81374...",0,NaN,0.0,ESG,214,NaN,6.158,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
2,"-37.813802999768036, 144.94222000027733","{""coordinates"": [144.94222000027733, -37.81380...",0,NaN,0.0,ESG,251,NaN,54.448,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
3,"-37.81380999995285, 144.9422400005824","{""coordinates"": [144.9422400005824, -37.813809...",0,NaN,0.0,ESG,259,NaN,98.143,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0
4,"-37.81351900001735, 144.94179300024945","{""coordinates"": [144.94179300024945, -37.81351...",0,NaN,0.0,ESG,77,NaN,18.280,NaN,...,0.0,0,0,NaN,NaN,NaN,20140916,NaN,0,0

In [66]:
# lighting data last updated at 20140916
raw_light['xdate'].drop_duplicates()

0    20140916
Name: xdate, dtype: int64

In [67]:
import json
raw_light['geo_type'] = raw_light['geo_shape'].apply(lambda x: json.loads(x)['type'])
raw_light.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106037 entries, 0 to 106036
Data columns (total 22 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   geo_point_2d  106037 non-null  object
 1   geo_shape     106037 non-null  object
 2   prop_id       106037 non-null  int64
 3   name          0 non-null       float64
 4   addresspt1    106037 non-null  float64
 5   xorg          106037 non-null  object
 6   ext_id        106037 non-null  int64
 7   asset_clas    0 non-null       float64
 8   label         106037 non-null  float64
 9   asset_type    0 non-null       float64
 10  easting       106037 non-null  float64
 11  northing      106037 non-null  float64
 12  str_id        106037 non-null  int64
 13  addresspt     106037 non-null  int64
 14  asset_subt    0 non-null       float64
 15  xsource       0 non-null       float64
 16  profile       0 non-null       float64
 17  xdate         106037 non-null  int64
 18  xdrawing      0 non-null       float64
 19  mcc_id        106037 non-null  int64
 20  roadseg_id    106037 non-null  int64
 21  geo_type      106037 non-null  object
dtypes: float64(11), int64(7), object(4)
memory usage: 17.8+ MB

In [68]:
# Columns with only 1 value
raw_light[[col for col in raw_light.columns if raw_light[col].nunique() == 1]].drop_duplicates()

,prop_id,addresspt1,xorg,easting,northing,str_id,addresspt,xdate,mcc_id,roadseg_id,geo_type
0,0,0.0,ESG,0.0,0.0,0,0,20140916,0,0,Point

In [69]:
light_df = raw_light[[col for col in raw_light.columns if raw_light[col].nunique() > 1]].copy()
light_df['latitude'] = light_df['geo_point_2d'].str.split(', ').str[0].astype(float)
light_df['longitude'] = light_df['geo_point_2d'].str.split(', ').str[1].astype(float)

light_df.head()

,geo_point_2d,geo_shape,ext_id,label,latitude,longitude
0,"-37.81373899955726, 144.9421289998664","{""coordinates"": [144.9421289998664, -37.813738...",210,6.549,-37.813739,144.942129
1,"-37.81374400011677, 144.94213900036905","{""coordinates"": [144.94213900036905, -37.81374...",214,6.158,-37.813744,144.942139
2,"-37.813802999768036, 144.94222000027733","{""coordinates"": [144.94222000027733, -37.81380...",251,54.448,-37.813803,144.942220
3,"-37.81380999995285, 144.9422400005824","{""coordinates"": [144.9422400005824, -37.813809...",259,98.143,-37.813810,144.942240
4,"-37.81351900001735, 144.94179300024945","{""coordinates"": [144.94179300024945, -37.81351...",77,18.280,-37.813519,144.941793

In [70]:
light_df['geo_shape'].value_counts()

geo_shape
{"coordinates": [144.9702759997199, -37.80109000004725], "type": "Point"}      1017
{"coordinates": [144.9888309998181, -37.81247299958573], "type": "Point"}       582
{"coordinates": [144.98933399955305, -37.81318699976632], "type": "Point"}      430
{"coordinates": [144.97094700016362, -37.81849700013838], "type": "Point"}      261
{"coordinates": [144.92446900052795, -37.79896899953943], "type": "Point"}      153
                                                                               ...
{"coordinates": [144.93848600051092, -37.777256999506704], "type": "Point"}       1
{"coordinates": [144.938872999602, -37.77807599974197], "type": "Point"}          1
{"coordinates": [144.93850699942126, -37.77726099968011], "type": "Point"}        1
{"coordinates": [144.93888099969053, -37.7780800003798], "type": "Point"}         1
{"coordinates": [144.92438300037776, -37.797155999966655], "type": "Point"}       1
Name: count, Length: 97405, dtype: int64

In [ ]:
light_df[light_df['geo_shape']=='{"coordinates": [144.9702759997199, -37.80109000004725], "type": "Point"}']

In [71]:
# drop duplicates based on geo_shape, keeping only the record with latest ext_id
light_df = light_df.sort_values('ext_id', ascending=False)
light_df = light_df.drop_duplicates(subset=['geo_shape'])

In [127]:
light_df.head()

,geo_point_2d,geo_shape,ext_id,label,latitude,longitude,lat_map,long_map
68412,"-37.81910299993481, 144.94717399954112","{""coordinates"": [144.94717399954112, -37.81910...",106037,18.280,-37.819103,144.947174,-37.819,144.947
56442,"-37.81910499968281, 144.94717700002684","{""coordinates"": [144.94717700002684, -37.81910...",106029,12.512,-37.819105,144.947177,-37.819,144.947
71876,"-37.81910800031837, 144.94717900034982","{""coordinates"": [144.94717900034982, -37.81910...",106028,12.414,-37.819108,144.947179,-37.819,144.947
75245,"-37.81911000004645, 144.9471819997004","{""coordinates"": [144.9471819997004, -37.819110...",106027,12.317,-37.819110,144.947182,-37.819,144.947
51779,"-37.81911200038785, 144.9471840004734","{""coordinates"": [144.9471840004734, -37.819112...",106026,12.414,-37.819112,144.947184,-37.819,144.947

In [72]:
light_df.nunique()

geo_point_2d    97405
geo_shape       97405
ext_id          97405
label            1016
latitude        97401
longitude       97398
dtype: int64

In [ ]:
light_df[light_df['geo_shape']=='{"coordinates": [144.9702759997199, -37.80109000004725], "type": "Point"}']

,geo_point_2d,geo_shape,ext_id,label,latitude,longitude
15244,"-37.80109000004725, 144.9702759997199","{""coordinates"": [144.9702759997199, -37.801090...",15628,1.564,-37.80109,144.970276

In [ ]:
# Prepare export data
light_export = light_df[['latitude', 'longitude', 'ext_id', 'label']].rename(columns={'label': 'emitted_lux_level'})
light_export.to_csv('street_light.csv', index=False)

In [114]:
agg_light_df = light_df.copy()
agg_light_df['lat_map'] = round(agg_light_df['latitude'] , 3)
agg_light_df['long_map'] = round(agg_light_df['longitude'] , 3)

# Testing: Postcode with australian_postcodes

In [107]:
import pandas as pd
postcodes = pd.read_csv('raw/australian_postcodes.csv')
vic_postcodes = postcodes[postcodes['state']=='VIC'] #Filter to VIC
vic_postcodes.head()

,id,postcode,locality,state,long,lat,dc,type,status,sa3,...,altitude,chargezone,phn_code,phn_name,lgaregion,lgacode,electorate,electoraterating,sed_code,sed_name
6194,4746,3000,MELBOURNE,VIC,144.982585,-37.814437,CITY DELIVERY CENTRE,Delivery Area,Updated 17-Mar-2024 AUSPOST,20604.0,...,27.332188,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan,24703.0,Melbourne (Northern Metropolitan)
6195,4747,3001,MELBOURNE,VIC,144.982585,-37.814437,CITY MAIL PROCESSING CENTRE,Post Office Boxes,Updated 17-Mar-2024 AUSPOST,20605.0,...,27.332188,V1,PHN203,NaN,Melbourne,24600.0,Maribyrnong,NaN,NaN,NaN
6196,4748,3002,EAST MELBOURNE,VIC,144.982585,-37.814437,CITY DELIVERY CENTRE,Delivery Area,Updated 17-Mar-2024 AUSPOST,20604.0,...,27.332188,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan,24703.0,Melbourne (Northern Metropolitan)
6197,4749,3003,WEST MELBOURNE,VIC,144.949592,-37.810871,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,15.316063,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan,24703.0,Melbourne (Northern Metropolitan)
6198,4750,3004,MELBOURNE,VIC,144.982585,-37.814437,CITY DELIVERY CENTRE,Delivery Area,Updated 17-Mar-2024 AUSPOST,20605.0,...,27.332188,V1,PHN203,South Eastern Melbourne,Melbourne,24600.0,Macnamara,Inner Metropolitan,26906.0,Prahran (Southern Metropolitan)

In [109]:
vic_postcodes = vic_postcodes[['postcode', 'locality', 'sa3name', 'sa4name', 'Lat_precise', 'Long_precise']]
vic_postcodes['lat'] = round(vic_postcodes['Lat_precise'], 3)
vic_postcodes['long'] = round(vic_postcodes['Long_precise'], 3)

In [ ]:
vic_postcodes = vic_postcodes[['postcode', 'long','lat', 'locality', 'sa3name', 'sa4name', 'Lat_precise', 'Long_precise']]
vic_postcodes[round(vic_postcodes['Lat_precise'], 3)==round(-37.819103, 3)]

,postcode,long,lat,locality,sa3name,sa4name,Lat_precise,Long_precise
6507,3135,145.248209,-37.819594,BEDFORD ROAD,Maroondah,Melbourne - Outer East,-37.819303,145.243920
8964,3766,145.384955,-37.817818,KALORAMA,Yarra Ranges,Melbourne - Outer East,-37.819494,145.386264
18497,8012,144.948039,-37.814719,DOCKLANDS,Melbourne City,Melbourne - Inner,-37.819000,144.947000

In [112]:
light_df['lat_map'] = round(light_df['latitude'] , 3)
light_df['long_map'] = round(light_df['longitude'] , 3)

light_postcode = pd.merge(
    light_df,
    vic_postcodes,
    left_on=['lat_map', 'long_map'],
    right_on=['lat', 'long'],
    how='left')

light_postcode.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97644 entries, 0 to 97643
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   geo_point_2d  97644 non-null  object
 1   geo_shape     97644 non-null  object
 2   ext_id        97644 non-null  int64
 3   label         97644 non-null  float64
 4   latitude      97644 non-null  float64
 5   longitude     97644 non-null  float64
 6   lat_map       97644 non-null  float64
 7   long_map      97644 non-null  float64
 8   postcode      1339 non-null   float64
 9   locality      1339 non-null   object
 10  sa3name       1339 non-null   object
 11  sa4name       1339 non-null   object
 12  Lat_precise   1339 non-null   float64
 13  Long_precise  1339 non-null   float64
 14  lat           1339 non-null   float64
 15  long          1339 non-null   float64
dtypes: float64(10), int64(1), object(5)
memory usage: 11.9+ MB

In [123]:
light_postcode[light_postcode['postcode'].isnull()].groupby(['lat_map', 'long_map']).count()

                  geo_point_2d  geo_shape  ext_id  label  latitude  longitude  \
lat_map long_map
-37.840 144.981            130        130     130    130       130        130
-37.839 144.979            226        226     226    226       226        226
        144.980             24         24      24     24        24         24
        144.981            328        328     328    328       328        328
-37.838 144.978            286        286     286    286       286        286
...                        ...        ...     ...    ...       ...        ...
-37.776 144.939            136        136     136    136       136        136
        144.940            311        311     311    311       311        311
        144.941            458        458     458    458       458        458
        144.942            234        234     234    234       234        234
-37.775 144.939             39         39      39     39        39         39

                  postcode  locality  sa3name  sa4name  Lat_precise  \
lat_map long_map
-37.840 144.981          0         0        0        0            0
-37.839 144.979          0         0        0        0            0
        144.980          0         0        0        0            0
        144.981          0         0        0        0            0
-37.838 144.978          0         0        0        0            0
...                    ...       ...      ...      ...          ...
-37.776 144.939          0         0        0        0            0
        144.940          0         0        0        0            0
        144.941          0         0        0        0            0
        144.942          0         0        0        0            0
-37.775 144.939          0         0        0        0            0

                  Long_precise  lat  long
lat_map long_map
-37.840 144.981              0    0     0
-37.839 144.979              0    0     0
        144.980              0    0     0
        144.981              0    0     0
-37.838 144.978              0    0     0
...                        ...  ...   ...
-37.776 144.939              0    0     0
        144.940              0    0     0
        144.941              0    0     0
        144.942              0    0     0
-37.775 144.939              0    0     0

[301 rows x 14 columns]

In [126]:
postcodes[round(postcodes['lat'],3)==-37.839]

,id,postcode,locality,state,long,lat,dc,type,status,sa3,...,altitude,chargezone,phn_code,phn_name,lgaregion,lgacode,electorate,electoraterating,sed_code,sed_name
8965,8971,3767,MOUNT DANDENONG,VIC,145.347505,-37.839387,MOOROOLBARK DC,Delivery Area,Updated 6-Feb-2020,21105.0,...,NaN,V1,PHN202,Eastern Melbourne,Yarra Ranges,27450.0,Casey,Rural,25101.0,Monbulk (Eastern Victoria)

In [120]:
light_postcode.groupby(['postcode','locality']).agg({'label': 'mean',
                                                     'latitude':'mean',
                                                     'longitude':'mean',
                                                     })

                             label   latitude   longitude
postcode locality
3000.0   MELBOURNE       82.844096 -37.814679  144.964312
3002.0   EAST MELBOURNE   4.004812 -37.815568  144.980045
8012.0   DOCKLANDS       37.627804 -37.819172  144.946950
9999.0   NORTH POLE      82.844096 -37.814679  144.964312